version: '3.6'

services:
  digitalhublms.sql:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HNTyV+6K?Z-EtahC

  digitalhublms.migrations:
    image: digitalhublms-migrations:v1
    build:
      context: .
      dockerfile: DigitalHubLMS.Migrations/Dockerfile
    ports:
      - 8083:80
      - 9445:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=digitalhublms.sql;Database=DigitalHubLMS_DB;User Id=sa;Password=M0hammed@Zak1;
    restart: on-failure  
    depends_on:
      - digitalhublms.sql
    volumes:
      - ./https:/https:ro

  digitalhublms.web:
    image: digitalhublms-web:v1
    build:
      context: .
      dockerfile: DigitalHubLMS.Web/Dockerfile
    ports:
      - 8081:80
      - 9443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=digitalhublms.sql;Database=DigitalHubLMS_DB;User Id=sa;Password=M0hammed@Zak1;
    restart: on-failure  
    depends_on:
      - digitalhublms.migrations
      - digitalhublms.sql
    volumes:
      - ./https:/https:ro

  digitalhublms.api:
    image: digitalhublms-api:v1
    build:
      context: .
      dockerfile: DigitalHubLMS.API/Dockerfile
    ports:
      - 8082:80
      - 9444:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456789
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=digitalhublms.sql;Database=DigitalHubLMS_DB;User Id=sa;Password=M0hammed@Zak1;
    restart: on-failure  
    depends_on:
      - digitalhublms.migrations
      - digitalhublms.sql
    volumes:
      - ./https:/https:ro

